apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: pro
spec:
  selector:
    component: uptime-kuma
  type: NodePort
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    nodePort: 3001
    protocol: TCP